# Generated by Django 4.2.5 on 2023-10-05 20:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personality",
            name="class_id",
        ),
    ]
