# Generated by Django 4.2.5 on 2023-10-05 21:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0003_personalitymeaning_remove_personality_abbreviation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="race",
            name="max_weight",
        ),
        migrations.RemoveField(
            model_name="race",
            name="min_weight",
        ),
    ]
