# Generated by Django 4.2.5 on 2023-10-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0004_remove_race_max_weight_remove_race_min_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="name",
            name="genus",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="name",
            name="sex",
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name="name",
            name="name",
            field=models.CharField(max_length=30),
        ),
    ]
