# Generated by Django 4.2.5 on 2023-10-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0005_name_genus_name_sex_alter_name_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="old",
            field=models.IntegerField(default=0),
        ),
    ]
