# Generated by Django 4.2.5 on 2023-10-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0006_race_old"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="maturity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="race",
            name="youth",
            field=models.IntegerField(default=0),
        ),
    ]
