# Generated by Django 4.2.5 on 2023-10-06 09:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0008_race_speed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="race",
            name="maturity",
        ),
    ]
