# Generated by Django 4.2.5 on 2023-10-06 09:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0009_remove_race_maturity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="features",
        ),
    ]
