# Generated by Django 4.2.5 on 2023-10-06 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0010_remove_class_features"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirstName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("sex", models.BooleanField(default=0)),
                ("genus", models.CharField(default="", max_length=30)),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rest.race"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LastName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rest.race"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Name",
        ),
    ]
