# Generated by Django 4.2.5 on 2023-10-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0015_attachment_ideal_worldview"),
    ]

    operations = [
        migrations.RenameField(
            model_name="race",
            old_name="name",
            new_name="race",
        ),
        migrations.AlterField(
            model_name="peculiarities",
            name="description",
            field=models.CharField(max_length=230),
        ),
    ]
