# Generated by Django 4.2.5 on 2023-10-11 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0017_remove_lastname_race_lastname_race"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firstname",
            name="race",
        ),
        migrations.RemoveField(
            model_name="lastname",
            name="race",
        ),
        migrations.AddField(
            model_name="firstname",
            name="race",
            field=models.ManyToManyField(default=None, to="rest.race"),
        ),
        migrations.AddField(
            model_name="lastname",
            name="race",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="rest.race",
            ),
        ),
    ]
