# Generated by Django 4.2.5 on 2023-10-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0018_remove_firstname_race_remove_lastname_race_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firstname",
            name="race",
            field=models.ManyToManyField(to="rest.race"),
        ),
    ]
