# Generated by Django 4.2.5 on 2023-10-11 10:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0019_alter_firstname_race"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firstname",
            name="race",
        ),
    ]
