# Generated by Django 4.2.5 on 2023-10-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0020_remove_firstname_race"),
    ]

    operations = [
        migrations.AddField(
            model_name="firstname",
            name="race",
            field=models.ManyToManyField(to="rest.race"),
        ),
    ]
