# Generated by Django 4.2.5 on 2023-10-11 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0023_lastname_race"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lastname",
            name="race",
        ),
    ]
