# Generated by Django 4.2.5 on 2023-10-11 17:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0027_lastname_race"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LastName",
        ),
    ]
