# Generated by Django 4.2.5 on 2023-10-11 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0028_delete_lastname"),
    ]

    operations = [
        migrations.CreateModel(
            name="LastName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("genus", models.CharField(default="", max_length=30)),
                (
                    "race",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rest.race",
                    ),
                ),
            ],
        ),
    ]
