# Generated by Django 4.2.5 on 2023-10-11 17:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0029_lastname"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LastName",
            new_name="LastNames",
        ),
    ]
