# Generated by Django 4.2.5 on 2023-10-11 17:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0030_rename_lastname_lastnames"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LastNames",
            new_name="LastName",
        ),
    ]
