# Generated by Django 4.2.5 on 2023-10-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0033_lastname_race"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="order_number",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name="background",
            name="order_number",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name="class",
            name="order_number",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name="firstname",
            name="order_number",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name="ideal",
            name="order_number",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name="lastname",
            name="order_number",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name="peculiarities",
            name="order_number",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name="personality",
            name="order_number",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name="race",
            name="order_number",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name="weakness",
            name="order_number",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name="worldview",
            name="order_number",
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
