# Generated by Django 4.2.5 on 2023-10-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0034_attachment_order_number_background_order_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="order_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="background",
            name="order_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="class",
            name="order_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="firstname",
            name="order_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ideal",
            name="order_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="peculiarities",
            name="order_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="personality",
            name="order_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="weakness",
            name="order_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="worldview",
            name="order_number",
            field=models.IntegerField(default=0),
        ),
    ]
