# Generated by Django 4.2.5 on 2023-10-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0035_alter_attachment_order_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attachment",
            old_name="order_number",
            new_name="number",
        ),
        migrations.RenameField(
            model_name="background",
            old_name="order_number",
            new_name="number",
        ),
        migrations.RenameField(
            model_name="class",
            old_name="order_number",
            new_name="number",
        ),
        migrations.RenameField(
            model_name="firstname",
            old_name="order_number",
            new_name="number",
        ),
        migrations.RenameField(
            model_name="ideal",
            old_name="order_number",
            new_name="number",
        ),
        migrations.RenameField(
            model_name="peculiarities",
            old_name="order_number",
            new_name="number",
        ),
        migrations.RenameField(
            model_name="personality",
            old_name="order_number",
            new_name="number",
        ),
        migrations.RenameField(
            model_name="weakness",
            old_name="order_number",
            new_name="number",
        ),
        migrations.RenameField(
            model_name="worldview",
            old_name="order_number",
            new_name="number",
        ),
        migrations.RemoveField(
            model_name="lastname",
            name="order_number",
        ),
        migrations.RemoveField(
            model_name="race",
            name="order_number",
        ),
        migrations.AddField(
            model_name="lastname",
            name="number",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="race",
            name="number",
            field=models.IntegerField(default=0),
        ),
    ]
