# Generated by Django 4.2.5 on 2023-10-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0036_rename_order_number_attachment_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lastname",
            name="race",
        ),
        migrations.AddField(
            model_name="lastname",
            name="race",
            field=models.ManyToManyField(to="rest.race"),
        ),
    ]
