# Generated by Django 4.2.5 on 2023-10-11 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0037_remove_lastname_race_lastname_race"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lastname",
            name="race",
        ),
    ]
