# Generated by Django 4.2.5 on 2023-10-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest", "0038_remove_lastname_race"),
    ]

    operations = [
        migrations.AddField(
            model_name="lastname",
            name="race",
            field=models.ManyToManyField(to="rest.race"),
        ),
    ]
