# Generated by Django 4.2.5 on 2023-10-15 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0039_lastname_race'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='race',
            new_name='name',
        ),
    ]
