import { TheHeader } from '@/components/TheHeader'
import './globals.css'
import type { Metadata } from 'next'
import { PT_Serif_Caption, Prata } from 'next/font/google'
import { TheFooter } from '@/components/TheFooter'


const prata = Prata({weight: ['400'], subsets: ['cyrillic']})
const serif = PT_Serif_Caption({weight: ['400'],subsets: ['cyrillic']})


export const metadata: Metadata = {
  title: 'DungeonGen | Main page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={prata.className}>

        <div className='wrapper'>
          <TheHeader />
          <main className='container'>
          {children}
          </main>
          <TheFooter />
        </div>
        </body>
    </html>
  )
}
